bookbyte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("models.urls")),
    path("", include("accounts.urls")),
    path("books/", include("books.urls")),
    path("staff/", include("staff.urls")),
    path("requisitions/", include("requisitions.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.books, name="books"),
    path("<slug:slug>/", views.book, name="book"),
    path("authors/<slug:slug>/", views.author, name="author"),
]

books/models/author.py
import uuid
from autoslug import AutoSlugField
from django.db import models

from models.models import Country


class Author(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birthdate = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True)
    biography = models.TextField(null=True, blank=True)
    personal_website = models.URLField(blank=True, null=True)
    picture = models.ImageField(upload_to="authors/", null=True, blank=True)
    slug = AutoSlugField(populate_from="get_full_name", unique=True,
                         db_index=True, editable=False, null=True)

    class Meta:
        ordering = ["-created"]

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.get_full_name()

books/models/book.py
from django.db import models
from django.core.validators import RegexValidator

from models.models import Content
from .author import Author


class Book(Content):
    isbn = models.CharField(max_length=13, validators=[
        RegexValidator(regex="^(97(8|9))?\d{9}(\d|X)$", message="Insira um ISBN.")])
    pages = models.PositiveIntegerField()
    format = models.CharField(max_length=10, choices=[(
        "hardcover", "Capa Dura"), ("paperback", "Capa Mole")])
    author = models.ManyToManyField(Author)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title

books/forms.py
from django.forms import ModelForm
from django import forms

from .models import Book, Author


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "genre", "publisher", "publication_date", "summary",
                  "isbn", "cover", "pages", "quantity", "language",
                  "format"]

        labels = {
            "title": "Título",
            "author": "Autor",
            "genre": "Géneros",
            "publisher": "Editora",
            "publication_date": "Data de Publicação",
            "summary": "Sinopse",
            "isbn": "ISBN",
            "cover": "Capa",
            "pages": "Páginas",
            "quantity": "Quantidade",
            "language": "Linguagem",
            "format": "Formato"
        }

        widgets = {
            'publication_date': forms.DateInput(attrs={'type': 'date'}),
        }


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ["first_name", "last_name", "birthdate",
                  "country", "biography", "personal_website", "picture"]

        labels = {
            "first_name": "Nome",
            "last_name": "Apelido",
            "birthdate": "Data de Nascimento",
            "country": "Nacionalidade",
            "biography": "Biografia",
            "personal_website": "Website Pessoal",
            "picture": "Foto"
        }

        widgets = {
            'birthdate': forms.DateInput(attrs={'type': 'date'}),
        }

books/views.py
from django.shortcuts import render, redirect

from .models import Book, Author
from .filters import BookFilter
from .utils import paginateBooks


def books(request):
    books = Book.objects.all()
    myFilter = BookFilter(request.GET, queryset=books)
    books = myFilter.qs
    custom_range, books = paginateBooks(request, books, 16)

    myFilter.form.fields['genre'].label = "Género"
    myFilter.form.fields['publisher'].label = "Editora"
    myFilter.form.fields['language'].label = "Idioma"

    context = {
        "books": books,
        "myFilter": myFilter,
        "custom_range": custom_range,
        "reset_form_redirect": "books"
    }

    return render(request, "books/books.html", context)


def book(request, slug):
    book = Book.objects.get(slug=slug)
    context = {
        "book": book
    }

    return render(request, "books/book-detail.html", context)


def author(request, slug):
    author = Author.objects.get(slug=slug)
    context = {
        "author": author
    }

    return render(request, "books/author-detail.html", context)

books/templates/books/author-detail.html
{% extends "main.html" %}
{% load static %}

{% block title %}{{author}}{% endblock title %}


{% block styles %}
<link rel="stylesheet" href="{% static "books/detail.css" %}">
<link rel="stylesheet" href="{% static "books/author-detail.css" %}">
{% endblock styles %}


{% block content %}
{% include "navbar.html" %}

<main>
    <section class="column--1">
        {% if author.picture %}
        <img src="{{author.picture.url}}" alt="{{author}} Foto" />
        {% endif %}
        <div>
          <p>Data de Nascimento</p>
          <p id="publication-date">{{ author.birthdate|date:"d F Y"}}</p>
        </div>
    </section>

    <section class="column--2">
        <div class="header">
            <img src="{% static "icons/user-36px-teal.svg" %}" alt="" />
            <h2>{{author}}</h2>
        </div>
        <p>{{author.biography}}</p>
        <ul>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              <span>Nacionalidade: </span>
              <img src="{{author.country.flag.url}}" alt="" id="flag" />
            </li>

            {% if author.personal_website %}
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              <a href="{{author.personal_website}}" id="website">Website Pessoal</a>
            </li>
            {% endif %}
        </ul>

        <section class="books-section">
            <div class="header">
                <img src="./content/icons/book-24px-teal.svg" alt="" />
                <h3>Livros</h3>
            </div>

            <ul class="books-list">
                {% for book in author.book_set.all %}
                <li>
                    <img src="{{book.cover.url}}" alt="" />
                    <a href="{% url "book" book.slug %}">
                      <h4>{{book.title}}</h4>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
    </section>
</main>



{% include "footer.html" %}
{% endblock content%}

books/templates/books/book-detail.html
{% extends "main.html" %}
{% load static %}

{% block title %}{{ book.title }}{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static "books/detail.css" %}">
<link rel="stylesheet" href="{% static "books/book-detail.css" %}">
{% endblock styles %}

{% block content %}
{% include "navbar.html" %}

<main>
    <section class="column--1">
        <img src="{{ book.cover.url }}" alt="{{ book.title }} Capa" />
        <div>
          <p>Primeira publicação</p>
          <p id="publication-date">{{ book.publication_date|date:"d F Y"}}</p>
        </div>
    </section>

    <section class="column--2">
        <div class="header">
            <img src="{% static "icons/book-open-36px-teal.svg" %}" alt="Ícone livro" />
            <h2>{{ book.title }}</h2>
        </div>
        <p>
            {{book.summary}}
        </p>
        <ul>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              Editora: <a href="{{book.publisher.website}}"><strong>{{book.publisher}}</strong></a>
            </li>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              ISBN: <strong>{{book.isbn}}</strong>
            </li>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              <span>Idioma: </span>
              <img src="{{book.language.flag.url}}" alt="" id="flag" />
            </li>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              Encadernação: <strong>{{book.get_format_display}}</strong>
            </li>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              Páginas: <strong>{{book.pages}}</strong>
            </li>
            <li>
              <img src="{% static "icons/check-circle-24px-teal.svg" %}" alt="" />
              Quantidade: <strong>{{book.quantity}}</strong>
            </li>
        </ul>
        <a href="#">
            <button data-content={{book.id}} data-action="add" class="btn btn--medium update-cart" id="btn-basket">Adicionar</button>
        </a>

        {% for author in book.author.all %}
        <section class="author-section">
            <div class="author-description">
                <p class="heading">Nome:</p>
                <h2>{{author}}</h2>
                <p class="heading">Sobre o autor:</p>
                <p>
                    {{author.biography|truncatechars:250}}
                </p>
                <a href="{% url "author" author.slug %}">Saber mais</a>
            </div>
            <div class="author-picture">
                <img src="{{author.picture.url}}" alt="" />
            </div>
        </section>           
        {% endfor %}
    </section>

    <section class="column--3"></section>
</main>

{% include "footer.html" %}
{% endblock content %}

books/templates/books/books.html
{% extends "main.html" %}
{% load static %}

{% block title %}Livros{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static "books/books.css" %}">
<link rel="stylesheet" href="{% static "books/search-book.css" %}">
{% endblock styles %}

{% block content %}
{% include "navbar.html" %}

<header>
    <h2>Livros</h2>
    {% include "books/search-book.html" with redirect="books"%}
</header>

<main>
    <ul class="products">
        {% for book in books %}
        <div class="product--card">
            <a href="{% url "book" book.slug %}" class="product--link">
              <img src="{{book.cover.url}}" alt="" />
              <ul class="product--description">
                <li>
                  <i class="ph ph-book"></i>
                  <span class="title"><strong>{{book.title|truncatechars:16}}</strong></span>
                </li>
                <li>
                  <i class="ph ph-user"></i>
                  {% for author in book.author.all %}
                  <span>{{author|truncatechars:8}}</span>
                  {% endfor %}
                </li>
                <li>
                  <i class="ph ph-file"></i>
                  <span>{{book.pages}} páginas</span>
                </li>
                <li>
                  <i class="ph ph-buildings"></i>
                  <span>{{book.publisher}}</span>
                </li>
                <li>
                  <i class="ph ph-hash"></i>
                  <span>{{book.quantity}}</span>
                </li>
                <li>
                  <img src="{{book.language.flag.url}}" alt="" class="flag" />
                </li>
              </ul>
            </a>
            <button data-content={{book.id}} data-action="add" class="btn btn--small update-cart">Adicionar</button>
        </div>
        {% endfor %}
    </ul>

  {% include "pagination.html" with queryset=books custom_range=custom_range%}
</main>
{% include "footer.html" %}

{% endblock content %}

books/templates/books/search-book.html
<form action="" id="search-form">
    {% for field in myFilter.form %}
    {% if field.label == "Search" %}
    {{field}}
    {% endif %}
    {% endfor %}

    <div class="select-filters">
      {% for field in myFilter.form %}
      {% if field.label != "Search" %}
      <div class="grid-item">
        <p>{{field.label}}</p>
        {{field}}
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <div class="form-btns">
      <button type="submit" class="btn btn--medium" id="btn-search">Pesquisar</button>
      <a href="{% url redirect %}" class="btn btn--small" id="btn-reset">Limpar</a>
    </div>
</form>